
(function () {
	
	const data = {
		method: '《国家学生体质健康标准》规范测试方法',
		allStudent: 555,
		menCount: 222,
		womenCount: 333,
		ratio: '2:3',
		averageScore: '88',
		improveRatio: '20%',
		ranking: 3,
		verygood: '90%',
		good: '10%',
		pass: '20%',
		unpass: '30%',
		improveScore: 45,
		gradeHighScore: '六',
		highScore: 99,
		gradeLowScore: '一',
		lowScore: 10,
		scoreDownGrades: '四',
		scoreUpGrades: '六',
		distanceScore: 30,
		downScoreMuchGrade: '一',
		downScoreMuch: 34,
		fivePartGoodRatio: '25%',
		fivePartHighAverageGrade: '六',
		fivePartHighAverageGradeScore: 99,
		fivePartLowScore: 66,
		fivePartLastLevelGrade: '五',
		fivePartDistanceScore: 30,
		fivePartDownGrade: '四',
		fivePartDownGradeScore: 40,
		fivePartMethod: '222',
		fivePartGradeA: '六',
		fivePartGradeB: '四',
		fivePartProjectHighScore: '跳绳 87',
		fivePartProjectLowScore: '50米跑 30',
		fivePartImproveProject: '肺活量',
		fivePartImproveProjectScore: '6.68',
		fivePartProject: '50*8',
		fivePartProjectDownScore: '20',
		fivePartStrongProjectA: '50*8',
		fivePartStrongProjectB: '50米跑',
		pieChart:{},
		barChart:{},
		lineChart:{},
		'BMI': {
			averageScore: 99,
			level: '提高',
			levelScore: 55,
			goodRatio: '89%',
			fatRatio: '55%',
			lastLevelRatio: '34%',
			highScoreGrade: '六',
			highScore: 88,
			lowScoreGrade: '四',
			lowScore: 44,
		},
		'fei': {
			averageScore: 99,
			level: '提高',
			levelScore: 55,
			goodRatio: '89%',
			lastLevelRatio: '34%',
			highScoreGrade: '六',
			highScore: 88,
			lowScoreGrade: '四',
			lowScore: 44,

		},
		'50meter': {
			averageScore: 99,
			level: '提高',
			levelScore: 55,
			goodRatio: '89%',
			lastLevelRatio: '34%',
			highScoreGrade: '六',
			highScore: 88,
			lowScoreGrade: '四',
			lowScore: 44,
		},
		'zwtqq': {
			averageScore: 99,
			level: '提高',
			levelScore: 55,
			goodRatio: '89%',
			lastLevelRatio: '34%',
			highScoreGrade: '六',
			highScore: 88,
			lowScoreGrade: '四',
			lowScore: 44,
		},
		'ropeskipping': {
			averageScore: 99,
			level: '提高',
			levelScore: 55,
			goodRatio: '89%',
			lastLevelRatio: '34%',
			highScoreGrade: '六',
			highScore: 88,
			lowScoreGrade: '四',
			lowScore: 44,
		},
		'situp': {
			averageScore: 99,
			level: '提高',
			levelScore: 55,
			goodRatio: '89%',
			lastLevelRatio: '34%',
			highScoreGrade: '六',
			highScore: 88,
			lowScoreGrade: '四',
			lowScore: 44,
		},
		'50*8': {
			averageScore: 99,
			level: '提高',
			levelScore: 55,
			goodRatio: '89%',
			lastLevelRatio: '34%',
			highScoreGrade: '六',
			highScore: 88,
			lowScoreGrade: '四',
			lowScore: 44,
		},

	}
	setGlobalData('healthReport',data);
})();